#!/bin/bash
# mgropp, 2013-06-26
set -u

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
MEGAPD=/usr/local/bin/MegaPD

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

unconf_re='^Firmware state: Unconfigured\(good\)'
hotspare_re='^Firmware state: Hotspare, Spun Up'
good_re="^Firmware state: Online, Spun Up|$unconf_re|$hotspare_re"

return=0

total=`$MEGAPD | egrep ^Firmware\ state: | wc -l`
if [ $total -eq 0 ]
then
	echo "No drive information found?"
	return=$STATE_UNKNOWN
else
	good=`$MEGAPD | egrep "$good_re" | wc -l`
	if [ $total != $good ]
	then
		state=`$MEGAPD | egrep "$good_re"`
		state=${state#Firmware state: }
		devId=`$MEGAPD | egrep -B15 "^Firmware state: $state" | egrep '^Device Id:'`
		
		echo "Disk problems ($(( $total - $good ))/$total)! $devId -- $state"
		return=$STATE_CRITICAL
	fi
fi

if [ $return -eq 0 ]
then
	echo -n "RAID looks good ($good/$total"

	hotspare=`$MEGAPD | egrep "$hotspare_re" | wc -l`
	if [ $hotspare -gt 0 ]
	then
		echo -n ", $hotspare hotspares"
	fi

	unconfiguredGood=`$MEGAPD | egrep "$unconf_re" | wc -l`
	if [ $unconfiguredGood -gt 0 ]
	then
		echo -n ", $unconfiguredGood unconf."
	fi

	echo ")."
fi

exit $return
